---
rounds_idx: 0
reference_date_col_name: 'origin_date'
target_date_col_name: 'target_end_date'
horizon_col_name: 'horizon'
initial_checked_models: ['delphi-epicast', 'hist-avg']
disclaimer: "This is a sandbox forecast visualization. It is not designed to support an operational hub, but instead is designed for benchmarking and research purposes."
target_data_file_name: 'time-series.csv'
task_id_text:
  location:
    "US National": "US National"
    "HHS Region 1": "HHS Region 1"
    "HHS Region 2": "HHS Region 2"
    "HHS Region 3": "HHS Region 3"
    "HHS Region 4": "HHS Region 4"
    "HHS Region 5": "HHS Region 5"
    "HHS Region 6": "HHS Region 6"
    "HHS Region 7": "HHS Region 7"
    "HHS Region 8": "HHS Region 8"
    "HHS Region 9": "HHS Region 9"
    "HHS Region 10": "HHS Region 10"
