schema_version: https://raw.githubusercontent.com/hubverse-org/hubPredEvalsData/main/inst/schema/v1.0.0/config_schema.json
targets:
- target_id: ili perc
  metrics:
  - wis
  - ae_median
  - interval_coverage_50
  - interval_coverage_95
  relative_metrics:
  - wis
  - ae_median
  baseline: hist-avg
  disaggregate_by:
  - location
  - origin_date
  - horizon
  - target_end_date
eval_sets:
- eval_set_name: Validation seasons (15/16 - 16/17)
  round_filters:
    min: '2015-10-17'
    max: '2017-05-06'
- eval_set_name: Test seasons (17/18 - 19/20)
  round_filters:
    min: '2017-10-21'
    max: '2020-01-18'

