---
title: "Introduction"
---

This is a "Sandbox Hub", designed to support the [2025 NFIDD SISMID Nowcasting and Forecasting Workshop](https://nfidd.github.io/sismid/).

The pre-populated content of this modeling hub is a subset of the [archive](https://github.com/hubverse-org/flusight_hub_archive) of forecasts submitted to the US CDC's [FluSight](https://www.cdc.gov/flu-forecasting/index.html) Modeling Challenges from 2015 through 2020.
The data in this hub follows [Hubverse](https://hubverse.io/) data standards.


From 2013 through 2020, the FluSight challenges were based around forecasting Influenza-Like Illness (ILI).
Since 2021, once resumed after the COVID-19 pandemic, the [FluSight challenges](https://github.com/cdcepi/FluSight-forecast-hub) have focused on predicting hospitalizations due to influenza.

::: {style='display:flex; align-items: center; justify-content: center'}

[View The Forecasts](forecast.html){.btn .btn-primary role="button"}

:::

The purpose of this hub is to allow new forecasts to be submitted so they can be compared, in retrospect, against forecasts that were made in real-time.

:::{.callout-note}

Interested in submitting your own forecasts to benchmark them against the models contained here? Follow our [practice session for instructions](https://nfidd.github.io/sismid/sessions/hub-playground.html). 

:::

:::{.callout-warning}

The original FluSight forecasts contained in this hub were created in real-time, when the epidemiological surveillance data were not yet finalized. 
Retrospectively generated models that are not careful to only allow their model to see what data was available at a specific time will likely achieve a higher accuracy due to them seeing more finalized data. 

:::

